services:
  - type: web
    name: multi-tenant-rag-knowledge-base
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/api/health"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PRIMARY_LLM_PROVIDER
        value: groq
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: EMBEDDING_PROVIDER
        value: sentence_transformers
      - key: SEED_DEMO_DATA
        value: "false"
